language: python
git:
    depth: 5
matrix:
  include:
    - name: "Scan code with cobra"
      python: 3.6
      dist: xenial
      before_cache:
      cache:
      before_install:
      script: |
        bash ci/code_security_audit.sh
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial
    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
      dist: xenial
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.14.3  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - bash -x init_env.sh -p
        - source ~/.bashrc
        - pyenv global 3.7.3
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - bash init_env.sh -i
    # - name: "Python 3.7.3 on Windows"
    #   os: windows           # Windows 10.0.17134 N/A Build 17134
    #   language: shell       # 'language: python' is an error on Travis CI Windows
    #   before_install:
    #     - choco install python
    #     - python -m pip install --upgrade pip
    #     # - pip install configobj
    #   env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
addons:
  apt:
    packages:
    - openssl
    - curl
    - npm
  homebrew:
    packages:
    - openssl
    - curl
    - npm
install:
  - python --version
  - pip install -r requirements.txt
  - bash init_env.sh -i
script: |
  bash -x ci/ci_check.sh

